### ISSUE TITLE
Opening extraQL while another is running

### ISSUE THREAD

**Issue by Melodeiro** [PredatH0r/extraQL#4]
Would be great if there will be an option for (or maybe just following behaviour) starting QL instead of showing extraQL window if it was minimized. I have just renamed extraQL.exe link to "Quake Live" and use "autostart Quake live".
This will also fix problem with Steam Server Browser: when extraQL is already running, it will show up (if was minimized) and windows will keep extraQL focused when QL started, so i need to do alt+tab or change focus to QL with mouse. I has Windows 7, if it is important.

**Comment by Melodeiro** [comment]
Maybe i should use "Close extraQL on QL exit" but sometimes it is easier to start SSB or QL from tray. Also it will not help with SSB problem, if QL is already running (and extraQL due to an option from SSB).

**Comment by PredatH0r** [comment]
There were an issues in the past where it failed to detect already running instances. These should have been fixed since version 2.9.1.
Do you still encounter problems with a more recent version?

**Comment by Melodeiro** [comment]
I saw same bug before 2.9.1, if im not wrong, it just started new instances of extraQL. Now (2.12.1) there are other bad behaviour, which i am talking about. When extraQL are already running and hidden in tray, i am not able to start QL from just desktop extraQL icon. Instead i get extraQL maximized (showing up). Also, if i connecting to servers from SSB, there are same behaviour: extraQL shows from tray if was hidden before, but connecting works. Even more, if my QL is already running, after connect via SSB, extraQL will pop ups above the game, because of stealing focus, so i need to Alt+Tab.

I think it is all the same issue, maybe implementing startup parameters eg "--no-maximize" and "--start-quake-live" will help, which can be added to command in SSB which starts extraQL, and also to desktop link. Or maybe extraQL option to "start QL instead of showing GUI when running" or something like that. Maybe there are better options for doing that, idk.

**Comment by PredatH0r** [comment]
SteamServerBrowser 2.19 no longer brings extraQL to the front when it is already running.
(extraQL already had a "-background" option, but SSB 2.18 didn't use it)

I'll have to think about the other changes and might add them to the next extraQL version (2.14)

**Comment by PredatH0r** [comment]
This should all be working now with 2.14.
If you have "autostart QL" enabled, starting another extraQL will no longer bring it to front but instead brings any open QL window to front or starts QL if it isn't running.
